server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres?options=-c%20search_path=mybatis_spring
    username: postgres
    password: 1234

mybatis:
  type-aliases-package: study.spring.mybatis_spring
#  mapper-locations: classpath:/study/spring/mybatis_spring/**/*Mapper.xml
  mapper-locations: classpath:/mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  pattern:
    # 날짜 및 시간 제거 패턴
    console: "[%t] %-5level %logger{36} - %msg%n"
  level:
    study.spring.mybatis_spring: debug
    org:
      mybatis: trace
      apache:
        ibatis: trace
      springframework:
        transaction:
          support: trace
          interceptor: trace
        jdbc:
          support:
            JdbcTransactionManager: trace
          datasource:
            DataSourceTransactionManager: trace
    sun: info
#    com:
#      zaxxer:
#        hikari: trace